# Generated by Django 4.2.20 on 2025-10-30 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversaciones', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColaAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activo', models.BooleanField(default=True)),
                ('max_conversaciones', models.IntegerField(default=5)),
                ('conversaciones_actuales', models.IntegerField(default=0)),
                ('ultima_asignacion', models.DateTimeField(blank=True, null=True)),
                ('peso_asignacion', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ['conversaciones_actuales', 'ultima_asignacion'],
            },
        ),
        migrations.CreateModel(
            name='MetricasOperador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conversaciones_atendidas', models.IntegerField(default=0)),
                ('tiempo_respuesta_promedio', models.FloatField(default=0.0)),
                ('satisfaccion_promedio', models.FloatField(default=0.0)),
                ('conversaciones_cerradas', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Métricas de Operadores',
            },
        ),
        migrations.AddField(
            model_name='conversacion',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='fecha_primera_respuesta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='normal', max_length=10),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='satisfaccion',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], null=True),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='tiempo_espera_segundos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='conversacion',
            name='tiempo_respuesta_segundos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('cerrada', 'Cerrada')], default='pendiente', max_length=10),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['estado', 'prioridad'], name='conversacio_estado_e7234d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['operador_asignado', 'estado'], name='conversacio_operado_4501e2_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['fecha_inicio'], name='conversacio_fecha_i_adffb0_idx'),
        ),
        migrations.AddField(
            model_name='metricasoperador',
            name='operador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='metricas_conversaciones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='colaasignacion',
            name='operador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cola_asignacion', to=settings.AUTH_USER_MODEL),
        ),
    ]
