# Generated by Django 4.2.20 on 2025-10-31 22:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversaciones', '0002_colaasignacion_metricasoperador_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevaConversacionAlerta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vista', models.BooleanField(default=False)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversaciones.conversacion')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('conversacion', 'operador')},
            },
        ),
    ]
