# Generated by Django 4.2.20 on 2025-10-31 23:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('conversaciones', '0003_nuevaconversacionalerta'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialAlertaConversacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('NUEVA_CONVERSACION', 'Nueva Conversación'), ('NUEVO_MENSAJE', 'Nuevo Mensaje'), ('RIESGO_CRITICO', 'Riesgo Crítico')], max_length=20)),
                ('mensaje', models.CharField(max_length=200)),
                ('vista', models.BooleanField(default=False)),
                ('fecha_vista', models.DateTimeField(blank=True, null=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='conversaciones.conversacion')),
                ('operador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado'],
            },
        ),
    ]
