# Generated by Django 4.2.20 on 2025-11-11 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('conversaciones', '0005_merge_20251104_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colaasignacion',
            name='activo',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='colaasignacion',
            name='conversaciones_actuales',
            field=models.IntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='colaasignacion',
            name='ultima_asignacion',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='dni_ciudadano',
            field=models.CharField(blank=True, db_index=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('activa', 'Activa'), ('cerrada', 'Cerrada')], db_index=True, default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='fecha_asignacion',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='fecha_cierre',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='fecha_inicio',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='prioridad',
            field=models.CharField(choices=[('baja', 'Baja'), ('normal', 'Normal'), ('alta', 'Alta'), ('urgente', 'Urgente')], db_index=True, default='normal', max_length=10),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='satisfaccion',
            field=models.IntegerField(blank=True, choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='tiempo_respuesta_segundos',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='conversacion',
            name='tipo',
            field=models.CharField(choices=[('anonima', 'Anónima'), ('personal', 'Personal')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='fecha_envio',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='leido',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='remitente',
            field=models.CharField(choices=[('ciudadano', 'Ciudadano'), ('operador', 'Operador')], db_index=True, max_length=10),
        ),
        migrations.AddIndex(
            model_name='colaasignacion',
            index=models.Index(fields=['activo', 'conversaciones_actuales'], name='conversacio_activo_bcbccd_idx'),
        ),
        migrations.AddIndex(
            model_name='colaasignacion',
            index=models.Index(fields=['operador', 'activo'], name='conversacio_operado_8810fd_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['tipo', 'estado'], name='conversacio_tipo_c9c2e6_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['dni_ciudadano'], name='conversacio_dni_ciu_ae4058_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['satisfaccion'], name='conversacio_satisfa_c55d9d_idx'),
        ),
        migrations.AddIndex(
            model_name='conversacion',
            index=models.Index(fields=['fecha_cierre'], name='conversacio_fecha_c_c9573f_idx'),
        ),
        migrations.AddIndex(
            model_name='historialalertaconversacion',
            index=models.Index(fields=['operador', 'vista', '-creado'], name='conversacio_operado_fe96be_idx'),
        ),
        migrations.AddIndex(
            model_name='historialalertaconversacion',
            index=models.Index(fields=['conversacion', 'tipo'], name='conversacio_convers_3e0cca_idx'),
        ),
        migrations.AddIndex(
            model_name='historialalertaconversacion',
            index=models.Index(fields=['tipo', 'vista'], name='conversacio_tipo_ce9dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='historialasignacion',
            index=models.Index(fields=['conversacion', '-fecha_asignacion'], name='conversacio_convers_e53dde_idx'),
        ),
        migrations.AddIndex(
            model_name='historialasignacion',
            index=models.Index(fields=['operador_nuevo', '-fecha_asignacion'], name='conversacio_operado_29ebc8_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion', 'fecha_envio'], name='conversacio_convers_36806d_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['remitente', 'leido'], name='conversacio_remiten_17239a_idx'),
        ),
        migrations.AddIndex(
            model_name='mensaje',
            index=models.Index(fields=['conversacion', 'leido'], name='conversacio_convers_4a506b_idx'),
        ),
        migrations.AddIndex(
            model_name='metricasoperador',
            index=models.Index(fields=['operador'], name='conversacio_operado_9b70a5_idx'),
        ),
        migrations.AddIndex(
            model_name='metricasoperador',
            index=models.Index(fields=['fecha_actualizacion'], name='conversacio_fecha_a_2bd3f7_idx'),
        ),
        migrations.AddIndex(
            model_name='nuevaconversacionalerta',
            index=models.Index(fields=['operador', 'vista'], name='conversacio_operado_3a0895_idx'),
        ),
        migrations.AddIndex(
            model_name='nuevaconversacionalerta',
            index=models.Index(fields=['conversacion', 'vista'], name='conversacio_convers_5927c1_idx'),
        ),
    ]
