# Generated by Django 4.2.20 on 2025-10-24 22:12

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0003_dispositivored'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('dni', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=120)),
                ('apellido', models.CharField(db_index=True, max_length=120)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(blank=True, max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('domicilio', models.CharField(blank=True, max_length=240)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Ciudadano',
                'verbose_name_plural': 'Ciudadanos',
            },
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('matricula', models.CharField(blank=True, max_length=60)),
                ('rol', models.CharField(blank=True, max_length=80)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesional',
                'verbose_name_plural': 'Profesionales',
            },
        ),
        migrations.CreateModel(
            name='LegajoAtencion',
            fields=[
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(default=core.models.generate_codigo, max_length=36, unique=True)),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_SEGUIMIENTO', 'En seguimiento'), ('DERIVADO', 'Derivado'), ('CERRADO', 'Cerrado')], default='ABIERTO', max_length=20)),
                ('fecha_apertura', models.DateField(auto_now_add=True)),
                ('fecha_cierre', models.DateField(blank=True, null=True)),
                ('confidencialidad', models.CharField(choices=[('NORMAL', 'Normal'), ('RESTRINGIDA', 'Restringida')], default='NORMAL', max_length=20)),
                ('notas', models.TextField(blank=True)),
                ('via_ingreso', models.CharField(choices=[('ESPONTANEA', 'Consulta espontánea'), ('DERIVACION', 'Derivación'), ('JUDICIAL', 'Judicial'), ('HOSPITAL', 'Hospital/Guardia')], default='ESPONTANEA', max_length=20)),
                ('fecha_admision', models.DateField(auto_now_add=True)),
                ('plan_vigente', models.BooleanField(default=False)),
                ('nivel_riesgo', models.CharField(choices=[('BAJO', 'Bajo'), ('MEDIO', 'Medio'), ('ALTO', 'Alto')], default='BAJO', max_length=20)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legajos', to='legajos.ciudadano')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legajos', to='core.dispositivored')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legajos_responsable', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Legajo de Atención',
                'verbose_name_plural': 'Legajos de Atención',
            },
        ),
        migrations.CreateModel(
            name='Consentimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('texto', models.TextField()),
                ('firmado_por', models.CharField(max_length=160)),
                ('fecha_firma', models.DateField()),
                ('archivo', models.FileField(blank=True, null=True, upload_to='consentimientos/')),
                ('vigente', models.BooleanField(default=True)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legajos.ciudadano')),
            ],
            options={
                'verbose_name': 'Consentimiento',
                'verbose_name_plural': 'Consentimientos',
            },
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['dni'], name='legajos_ciu_dni_4e1a21_idx'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['apellido', 'nombre'], name='legajos_ciu_apellid_2efcc7_idx'),
        ),
        migrations.AddIndex(
            model_name='legajoatencion',
            index=models.Index(fields=['ciudadano', 'dispositivo'], name='legajos_leg_ciudada_ecfe11_idx'),
        ),
        migrations.AddIndex(
            model_name='legajoatencion',
            index=models.Index(fields=['estado'], name='legajos_leg_estado_38174b_idx'),
        ),
        migrations.AddIndex(
            model_name='legajoatencion',
            index=models.Index(fields=['nivel_riesgo', 'fecha_admision'], name='legajos_leg_nivel_r_bb2a9c_idx'),
        ),
    ]
