# Generated by Django 4.2.20 on 2025-10-25 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'No binario')], max_length=1),
        ),
    ]
