# Generated by Django 4.2.20 on 2025-10-25 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0002_alter_ciudadano_genero'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluacionInicial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('situacion_consumo', models.TextField(blank=True, help_text='Descripción de la situación actual de consumo', verbose_name='Situación de Consumo')),
                ('antecedentes', models.TextField(blank=True, help_text='Antecedentes médicos, psiquiátricos y de consumo', verbose_name='Antecedentes')),
                ('red_apoyo', models.TextField(blank=True, help_text='Descripción de la red de apoyo familiar y social', verbose_name='Red de Apoyo')),
                ('condicion_social', models.TextField(blank=True, help_text='Situación socioeconómica, vivienda, trabajo, educación', verbose_name='Condición Social')),
                ('tamizajes', models.JSONField(blank=True, help_text='Resultados de tamizajes aplicados (ej: ASSIST, PHQ-9)', null=True, verbose_name='Tamizajes')),
                ('riesgo_suicida', models.BooleanField(default=False, help_text='Indica si presenta riesgo suicida', verbose_name='Riesgo Suicida')),
                ('violencia', models.BooleanField(default=False, help_text='Indica si presenta situación de violencia', verbose_name='Situación de Violencia')),
                ('legajo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluacion', to='legajos.legajoatencion')),
            ],
            options={
                'verbose_name': 'Evaluación Inicial',
                'verbose_name_plural': 'Evaluaciones Iniciales',
                'indexes': [models.Index(fields=['riesgo_suicida'], name='legajos_eva_riesgo__96eaaf_idx'), models.Index(fields=['violencia'], name='legajos_eva_violenc_4ca778_idx')],
            },
        ),
    ]
