# Generated by Django 4.2.20 on 2025-10-25 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('legajos', '0003_evaluacioninicial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=240)),
                ('indicador_exito', models.CharField(blank=True, max_length=240)),
                ('cumplido', models.BooleanField(default=False)),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objetivos', to='legajos.legajoatencion')),
            ],
            options={
                'verbose_name': 'Objetivo',
                'verbose_name_plural': 'Objetivos',
            },
        ),
        migrations.CreateModel(
            name='SeguimientoContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('ENTREVISTA', 'Entrevista'), ('VISITA', 'Visita'), ('LLAMADA', 'Llamada'), ('TALLER', 'Taller')], max_length=40)),
                ('descripcion', models.TextField()),
                ('adherencia', models.CharField(blank=True, choices=[('ADECUADA', 'Adecuada'), ('PARCIAL', 'Parcial'), ('NULA', 'Nula')], max_length=20)),
                ('adjuntos', models.FileField(blank=True, null=True, upload_to='seguimientos/')),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='legajos.legajoatencion')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legajos.profesional')),
            ],
            options={
                'verbose_name': 'Seguimiento',
                'verbose_name_plural': 'Seguimientos',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['legajo', '-creado'], name='legajos_seg_legajo__102aed_idx'), models.Index(fields=['tipo'], name='legajos_seg_tipo_878489_idx')],
            },
        ),
        migrations.CreateModel(
            name='PlanIntervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('vigente', models.BooleanField(default=True)),
                ('actividades', models.JSONField(blank=True, help_text='Lista de actividades: [{"accion":"Entrevista","freq":"semanal","responsable":"operador"}]', null=True)),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='legajos.legajoatencion')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='legajos.profesional')),
            ],
            options={
                'verbose_name': 'Plan de Intervención',
                'verbose_name_plural': 'Planes de Intervención',
                'indexes': [models.Index(fields=['legajo', 'vigente'], name='legajos_pla_legajo__774a07_idx')],
            },
        ),
        migrations.CreateModel(
            name='EventoCritico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('SOBREDOSIS', 'Sobredosis'), ('CRISIS', 'Crisis aguda'), ('VIOLENCIA', 'Violencia'), ('INTERNACION', 'Internación')], max_length=40)),
                ('detalle', models.TextField()),
                ('notificado_a', models.JSONField(blank=True, help_text='Lista de familiares/autoridades notificadas', null=True)),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos', to='legajos.legajoatencion')),
            ],
            options={
                'verbose_name': 'Evento Crítico',
                'verbose_name_plural': 'Eventos Críticos',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['legajo', 'tipo'], name='legajos_eve_legajo__746e22_idx'), models.Index(fields=['-creado'], name='legajos_eve_creado_f8d037_idx')],
            },
        ),
        migrations.CreateModel(
            name='Derivacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('motivo', models.TextField()),
                ('urgencia', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='MEDIA', max_length=20)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ACEPTADA', 'Aceptada'), ('RECHAZADA', 'Rechazada')], default='PENDIENTE', max_length=20)),
                ('respuesta', models.CharField(blank=True, max_length=120)),
                ('fecha_aceptacion', models.DateField(blank=True, null=True)),
                ('destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_destino', to='core.dispositivored')),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='derivaciones', to='legajos.legajoatencion')),
                ('origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='derivaciones_origen', to='core.dispositivored')),
            ],
            options={
                'verbose_name': 'Derivación',
                'verbose_name_plural': 'Derivaciones',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['legajo', 'estado'], name='legajos_der_legajo__77c550_idx'), models.Index(fields=['urgencia'], name='legajos_der_urgenci_7d080c_idx')],
            },
        ),
        migrations.CreateModel(
            name='Adjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('object_id', models.UUIDField()),
                ('archivo', models.FileField(upload_to='adjuntos/')),
                ('etiqueta', models.CharField(blank=True, max_length=120)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Adjunto',
                'verbose_name_plural': 'Adjuntos',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='legajos_adj_content_fdffd8_idx')],
            },
        ),
    ]
