# Generated by Django 4.2.20 on 2025-11-04 22:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legajos', '0005_derivacion_actividad_destino_inscriptoactividad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaAusentismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('AUSENTISMO_3', '3 días consecutivos'), ('AUSENTISMO_5', '5 días consecutivos'), ('AUSENTISMO_SEMANAL', 'Más del 50% semanal')], max_length=20)),
                ('dias_ausente', models.PositiveIntegerField()),
                ('fecha_inicio_ausencia', models.DateField()),
                ('activa', models.BooleanField(default=True)),
                ('inscripto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas_ausentismo', to='legajos.inscriptoactividad')),
                ('vista_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_ausentismo_vistas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Ausentismo',
                'verbose_name_plural': 'Alertas de Ausentismo',
                'ordering': ['-creado'],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('PRESENTE', 'Presente'), ('AUSENTE', 'Ausente'), ('JUSTIFICADO', 'Ausente Justificado'), ('TARDANZA', 'Tardanza')], max_length=15)),
                ('observaciones', models.TextField(blank=True)),
                ('inscripto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='legajos.inscriptoactividad')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registro de Asistencia',
                'verbose_name_plural': 'Registros de Asistencia',
                'ordering': ['-fecha'],
                'unique_together': {('inscripto', 'fecha')},
            },
        ),
    ]
