# Generated by Django 4.2.20 on 2025-10-25 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legajos', '0005_create_responsable_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legajoatencion',
            name='responsable',
            field=models.ForeignKey(blank=True, help_text='Usuario con rol de Responsable asignado al legajo', limit_choices_to={'groups__name': 'Responsable'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legajos_responsable', to=settings.AUTH_USER_MODEL, verbose_name='Responsable'),
        ),
    ]
