# Generated by Django 4.2.20 on 2025-10-26 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0006_alertaeventocritico'),
        ('legajos', '0006_alter_legajoatencion_responsable'),
    ]

    operations = [
    ]
