# Generated by Django 4.2.20 on 2025-10-26 04:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legajos', '0007_merge_20251025_2102'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='alertaeventocritico',
            name='legajos_alertaeventocritico_evento_id_responsable_id_uniq',
        ),
        migrations.RenameIndex(
            model_name='alertaeventocritico',
            new_name='legajos_ale_respons_7e2a8a_idx',
            old_name='legajos_ale_respons_b8b8b8_idx',
        ),
        migrations.AlterField(
            model_name='alertaeventocritico',
            name='creado',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='alertaeventocritico',
            name='modificado',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterUniqueTogether(
            name='alertaeventocritico',
            unique_together={('evento', 'responsable')},
        ),
    ]
