# Generated by Django 4.2.20 on 2025-11-05 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('legajos', '0008_add_performance_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='derivacion',
            name='actividad_destino',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derivaciones', to='legajos.planfortalecimiento', verbose_name='Actividad Específica'),
        ),
    ]
