# Generated by Django 4.2.20 on 2025-10-28 17:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0002_dispositivored_encargados'),
        ('legajos', '0009_fix_responsable_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='VinculoFamiliar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo_vinculo', models.CharField(choices=[('PADRE', 'Padre'), ('MADRE', 'Madre'), ('HIJO', 'Hijo/a'), ('HERMANO', 'Hermano/a'), ('ABUELO', 'Abuelo/a'), ('TIO', 'Tío/a'), ('PRIMO', 'Primo/a'), ('PAREJA', 'Pareja'), ('EXPAREJA', 'Ex pareja'), ('CUÑADO', 'Cuñado/a'), ('YERNO', 'Yerno/Nuera'), ('SUEGRO', 'Suegro/a'), ('AMIGO', 'Amigo/a'), ('VECINO', 'Vecino/a'), ('REFERENTE', 'Referente comunitario'), ('TUTOR', 'Tutor legal'), ('OTRO', 'Otro')], max_length=20)),
                ('es_contacto_emergencia', models.BooleanField(default=False, help_text='Disponible para emergencias 24hs')),
                ('es_referente_tratamiento', models.BooleanField(default=False, help_text='Participa activamente en el tratamiento')),
                ('convive', models.BooleanField(default=False, help_text='Vive en el mismo domicilio')),
                ('telefono_alternativo', models.CharField(blank=True, help_text='Teléfono adicional para este vínculo', max_length=40)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre la relación')),
                ('activo', models.BooleanField(default=True, help_text='Vínculo activo')),
                ('ciudadano_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_como_principal', to='legajos.ciudadano')),
                ('ciudadano_vinculado', models.ForeignKey(help_text='Debe ser otro ciudadano registrado en el sistema', on_delete=django.db.models.deletion.CASCADE, related_name='vinculos_como_vinculado', to='legajos.ciudadano')),
            ],
            options={
                'verbose_name': 'Vínculo Familiar',
                'verbose_name_plural': 'Vínculos Familiares',
                'indexes': [models.Index(fields=['ciudadano_principal', 'activo'], name='legajos_vin_ciudada_12442d_idx'), models.Index(fields=['es_contacto_emergencia'], name='legajos_vin_es_cont_ea3d52_idx'), models.Index(fields=['es_referente_tratamiento'], name='legajos_vin_es_refe_228ff2_idx')],
                'unique_together': {('ciudadano_principal', 'ciudadano_vinculado', 'tipo_vinculo')},
            },
        ),
        migrations.CreateModel(
            name='ProfesionalTratante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('rol', models.CharField(choices=[('PSICOLOGO', 'Psicólogo/a'), ('PSIQUIATRA', 'Psiquiatra'), ('MEDICO', 'Médico/a'), ('TS', 'Trabajador/a Social'), ('OPERADOR', 'Operador/a Socioterapéutico'), ('COORDINADOR', 'Coordinador/a'), ('DIRECTOR', 'Director/a'), ('ENFERMERO', 'Enfermero/a'), ('TERAPISTA', 'Terapista Ocupacional'), ('ABOGADO', 'Abogado/a'), ('OTRO', 'Otro')], max_length=20)),
                ('es_responsable_principal', models.BooleanField(default=False, help_text='Responsable principal del caso')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('fecha_desasignacion', models.DateField(blank=True, help_text='Fecha cuando dejó de atender el caso', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre su participación')),
                ('dispositivo', models.ForeignKey(help_text='Dispositivo donde trabaja', on_delete=django.db.models.deletion.PROTECT, to='core.dispositivored')),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesionales_tratantes', to='legajos.legajoatencion')),
                ('usuario', models.ForeignKey(help_text='Usuario del sistema', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profesional Tratante',
                'verbose_name_plural': 'Profesionales Tratantes',
                'indexes': [models.Index(fields=['legajo', 'activo'], name='legajos_pro_legajo__fd356e_idx'), models.Index(fields=['usuario', 'activo'], name='legajos_pro_usuario_220169_idx'), models.Index(fields=['es_responsable_principal'], name='legajos_pro_es_resp_2ed784_idx')],
                'unique_together': {('legajo', 'usuario', 'rol')},
            },
        ),
        migrations.CreateModel(
            name='HistorialContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo_contacto', models.CharField(choices=[('LLAMADA', 'Llamada Telefónica'), ('EMAIL', 'Email'), ('VISITA_DOM', 'Visita Domiciliaria'), ('REUNION', 'Reunión Presencial'), ('VIDEO', 'Videollamada'), ('MENSAJE', 'Mensaje/WhatsApp')], max_length=20)),
                ('fecha_contacto', models.DateTimeField()),
                ('duracion_minutos', models.PositiveIntegerField(blank=True, help_text='Duración en minutos (para llamadas/reuniones)', null=True)),
                ('estado', models.CharField(choices=[('EXITOSO', 'Exitoso'), ('NO_CONTESTA', 'No contesta'), ('OCUPADO', 'Ocupado'), ('CANCELADO', 'Cancelado'), ('REPROGRAMADO', 'Reprogramado')], default='EXITOSO', max_length=20)),
                ('motivo', models.CharField(help_text='Motivo del contacto', max_length=200)),
                ('resumen', models.TextField(help_text='Resumen de la conversación/encuentro')),
                ('acuerdos', models.TextField(blank=True, help_text='Acuerdos alcanzados')),
                ('proximos_pasos', models.TextField(blank=True, help_text='Próximos pasos acordados')),
                ('participantes', models.TextField(blank=True, help_text='Otras personas presentes (para reuniones/visitas)')),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación del encuentro', max_length=200)),
                ('archivo_adjunto', models.FileField(blank=True, help_text='Grabación, foto, documento relacionado', null=True, upload_to='contactos/')),
                ('seguimiento_requerido', models.BooleanField(default=False, help_text='Requiere seguimiento posterior')),
                ('fecha_proximo_contacto', models.DateField(blank=True, help_text='Fecha sugerida para próximo contacto', null=True)),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_contactos', to='legajos.legajoatencion')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Contacto',
                'verbose_name_plural': 'Historial de Contactos',
                'ordering': ['-fecha_contacto'],
                'indexes': [models.Index(fields=['legajo', '-fecha_contacto'], name='legajos_his_legajo__775928_idx'), models.Index(fields=['tipo_contacto', 'estado'], name='legajos_his_tipo_co_3a29d8_idx'), models.Index(fields=['profesional', '-fecha_contacto'], name='legajos_his_profesi_d278ba_idx'), models.Index(fields=['seguimiento_requerido'], name='legajos_his_seguimi_0fe9a4_idx')],
            },
        ),
        migrations.CreateModel(
            name='DispositivoVinculado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('fecha_admision', models.DateField()),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVO', 'Activo'), ('EGRESADO', 'Egresado'), ('DERIVADO', 'Derivado'), ('ABANDONO', 'Abandono'), ('SUSPENDIDO', 'Suspendido')], default='ACTIVO', max_length=20)),
                ('observaciones', models.TextField(blank=True, help_text='Observaciones sobre la admisión')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.dispositivored')),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispositivos_vinculados', to='legajos.legajoatencion')),
                ('referente_dispositivo', models.ForeignKey(blank=True, help_text='Referente en el dispositivo', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dispositivo Vinculado',
                'verbose_name_plural': 'Dispositivos Vinculados',
                'indexes': [models.Index(fields=['legajo', 'estado'], name='legajos_dis_legajo__2d6cdb_idx'), models.Index(fields=['dispositivo', 'estado'], name='legajos_dis_disposi_d191fc_idx')],
                'unique_together': {('legajo', 'dispositivo', 'fecha_admision')},
            },
        ),
        migrations.CreateModel(
            name='ContactoEmergencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('nombre', models.CharField(max_length=120)),
                ('relacion', models.CharField(help_text='Relación con el ciudadano', max_length=100)),
                ('telefono_principal', models.CharField(max_length=40)),
                ('telefono_alternativo', models.CharField(blank=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('disponibilidad_24hs', models.BooleanField(default=True, help_text='Disponible las 24 horas')),
                ('prioridad', models.PositiveSmallIntegerField(default=1, help_text='Orden de prioridad (1=mayor prioridad)')),
                ('instrucciones_especiales', models.TextField(blank=True, help_text='Instrucciones especiales para contactar')),
                ('activo', models.BooleanField(default=True)),
                ('legajo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_emergencia', to='legajos.legajoatencion')),
            ],
            options={
                'verbose_name': 'Contacto de Emergencia',
                'verbose_name_plural': 'Contactos de Emergencia',
                'ordering': ['prioridad', 'nombre'],
                'indexes': [models.Index(fields=['legajo', 'activo', 'prioridad'], name='legajos_con_legajo__c0e60f_idx')],
            },
        ),
    ]
