# Generated by Django 4.2.20 on 2025-10-29 20:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('legajos', '0010_vinculofamiliar_profesionaltratante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertaCiudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('modificado', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(choices=[('RIESGO_ALTO', 'Riesgo Alto'), ('RIESGO_SUICIDA', 'Riesgo Suicida'), ('VIOLENCIA', 'Situación de Violencia'), ('SIN_CONTACTO', 'Sin Contacto Prolongado'), ('SIN_EVALUACION', 'Sin Evaluación Inicial'), ('SIN_PLAN', 'Sin Plan de Intervención'), ('EVENTO_CRITICO', 'Evento Crítico Reciente'), ('DERIVACION_PENDIENTE', 'Derivación Pendiente'), ('SIN_RED_FAMILIAR', 'Sin Red Familiar'), ('SIN_CONSENTIMIENTO', 'Sin Consentimiento'), ('CONTACTOS_FALLIDOS', 'Contactos Fallidos'), ('PLAN_VENCIDO', 'Plan Vencido')], max_length=30)),
                ('prioridad', models.CharField(choices=[('CRITICA', 'Crítica'), ('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], max_length=10)),
                ('mensaje', models.CharField(max_length=200)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('cerrada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas_cerradas', to=settings.AUTH_USER_MODEL)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='legajos.ciudadano')),
                ('legajo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='legajos.legajoatencion')),
            ],
            options={
                'verbose_name': 'Alerta de Ciudadano',
                'verbose_name_plural': 'Alertas de Ciudadanos',
                'ordering': ['-creado'],
                'indexes': [models.Index(fields=['ciudadano', 'activa'], name='legajos_ale_ciudada_b8fddb_idx'), models.Index(fields=['tipo', 'prioridad'], name='legajos_ale_tipo_3f099f_idx'), models.Index(fields=['legajo', 'activa'], name='legajos_ale_legajo__34c7e6_idx')],
            },
        ),
    ]
